repos:

  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.6
    hooks:
    - id: jupytext
      args: [--sync, --pipe, black]

  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.2.0
    hooks:
        - id: rm-unneeded-f-str

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [--fix]
        exclude: docs/samples/.*$
      - id: ruff-format
        types_or: [ python, pyi ]

  # - repo: https://github.com/psf/black-pre-commit-mirror
  #   rev: 24.10.0
  #   hooks:
  #     - id: black
  #       args: ["--config=pyproject.toml"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        exclude: poetry.lock
