repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.15.2
    hooks:
    - id: jupytext
      args: [--sync, --pipe, black]
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      additional_dependencies: [Flake8-pyproject]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
