repos:
  - repo: https://github.com/mwouts/jupytext
    rev: v1.16.1
    hooks:
    - id: jupytext
      args: [--sync, --pipe, black]
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      additional_dependencies: [Flake8-pyproject]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
