seed_everything: 100
ckpt_path: null

data:
   class_path: datasets.facornet.FaCoRNetDMTask3
   init_args:
     root_dir: data/rfiw2021-track3

model:
  class_path: models.facornet.FaCoRNetTask3
  init_args:
    list_dir: data/rfiw2021-track3/txt/
    model:
      class_path: models.facornet.FaCoR
      init_args:
        attention: models.attention.FaCoRAttention
