seed_everything: 100
ckpt_path: null

data:
   class_path: datasets.scl.SCLDataModuleTask3
   init_args:
     root_dir: data/fiw/track3
     batch_size: 20

model:
  class_path: models.scl.SCLTask3
  init_args:
    optimizer: SGD
    adamw_beta1: 0.9
    adamw_beta2: 0.999
    lr: 1e-4
    momentum: 0.9
    weight_decay: 0
    start_lr: 1e-10
    end_lr: 1e-10
    lr_factor: 0.75
    lr_steps: [8, 14, 25, 35, 40, 50, 60]
    warmup: 200
    cooldown: 400
    scheduler: null
    threshold: null
    anneal_strategy: cos
    weights: null
    model:
      class_path: models.base.SimpleModel
      init_args:
        model: adaface_ir_101
    loss: 
      class_path: losses.scl.HCL
      init_args:
        tau: 0.3
        alpha_neg: 0.8
    list_dir: data/fiw/track3/txt/
