remotes:
  rig-1:
    type: ssh
    description: RIG1
    host: localhost
    user: warley
    port: 8021
    guild-env: ~/.virtualenvs/research
    guild-home: ~/.guild
  rig-2:
    type: ssh
    description: RIG2
    host: localhost
    user: warley
    port: 8024
    guild-env: ~/.virtualenvs/kinship
    guild-home: ~/.guild
  rig-1-local:
    type: ssh
    description: RIG1
    host: rig-1
    user: warley
    guild-env: ~/.virtualenvs/research
    guild-home: ~/.guild
  rig-2-facor:
    type: ssh
    description: RIG2
    host: rig2
    user: warley
    guild-env: ~/.virtualenvs/facor
    guild-home: ~/.guild
